import type { HybridConfig, MiniAppCategory, MiniAppPermission } from '../../types/mini-app';
import { lines } from './config';

function defaultOrigins(website: string) {
  try { const url = new URL(website); return url.protocol === 'https:' ? [url.origin] : []; } catch { return []; }
}

export function ConfigFields({ value, onChange, section, categories = [], permissions = [] }: { value: HybridConfig; onChange: (value: HybridConfig) => void; section: number; categories?: MiniAppCategory[]; permissions?: MiniAppPermission[] }) {
  const set = <K extends keyof HybridConfig>(key: K, input: HybridConfig[K]) => onChange({ ...value, [key]: input });
  if (section === 0) return <div className="mini-form-grid">
    <label>Tên ứng dụng<input required maxLength={120} value={value.name} onChange={e => set('name', e.target.value)} /></label>
    <label>Slug<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" value={value.slug} onChange={e => set('slug', e.target.value)} /><small>Chữ thường, số và dấu gạch ngang.</small></label>
    <label>Danh mục<select value={value.categoryId ?? ''} onChange={e => set('categoryId', e.target.value || null)}><option value="">Chưa chọn danh mục</option>{categories.filter(c => c.isActive !== false).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
    <label>Logo URL<input type="url" value={value.iconUrl ?? ''} onChange={e => set('iconUrl', e.target.value)} /></label>
    <label>Ảnh bìa URL<input type="url" value={value.coverUrl ?? ''} onChange={e => set('coverUrl', e.target.value)} /></label>
    <label className="mini-full">Mô tả<textarea rows={4} maxLength={1000} value={value.description ?? ''} onChange={e => set('description', e.target.value)} /></label>
  </div>;
  if (section === 1) return <div className="mini-form-grid">
    <label className="mini-full">Website URL<input type="url" required value={value.webUrl} onChange={e => set('webUrl', e.target.value)} /><small>URL HTTPS công khai sẽ được mở trong Mini App.</small></label>
    <label className="mini-full">Domain được phép<textarea rows={4} value={value.allowedDomains.join('\n')} onChange={e => set('allowedDomains', lines(e.target.value).map(domain => domain.toLowerCase()))} /><small>Mỗi domain một dòng. Xác minh quyền sở hữu trước khi gửi duyệt.</small></label>
    <label className="mini-full">Callback URLs (nếu dùng SSO)<textarea rows={3} value={value.callbackUrls.join('\n')} onChange={e => onChange({ ...value, callbackUrls: lines(e.target.value), callbackUrl: lines(e.target.value)[0] ?? '' })} /><small>URL phải trùng chính xác callback phía máy chủ đối tác.</small></label>
  </div>;
  if (section === 2) return <div className="mini-stack">
    <fieldset className="mini-mode-options"><legend>Phương thức đăng nhập</legend>{[{ value: 'Independent' as const, name: 'Standard WebView', text: 'Người dùng đăng nhập bằng tài khoản của website. Không yêu cầu danh tính ANKT.' }, { value: 'AnktSso' as const, name: 'ANKT SSO', text: 'Website chủ động yêu cầu đăng nhập ANKT và tạo phiên riêng sau khi đổi mã.' }].map(mode => <label key={mode.value} className="mini-mode"><input type="radio" name="authenticationMode" checked={value.authenticationMode === mode.value} onChange={() => onChange({ ...value, authenticationMode: mode.value, allowedOrigins: value.allowedOrigins.length ? value.allowedOrigins : defaultOrigins(value.webUrl), permissions: mode.value === 'Independent' ? value.permissions.filter(code => !code.startsWith('identity.') && !code.startsWith('profile.')) : [...new Set([...value.permissions, 'identity.login'])] })} /><span><strong>{mode.name}</strong><small>{mode.text}</small></span></label>)}</fieldset>
    <label>Origins cho bridge<textarea rows={3} value={value.allowedOrigins.join('\n')} onChange={e => set('allowedOrigins', lines(e.target.value))} /><small>Ví dụ https://app.example.com. Chỉ origin đã xác minh được truy cập bridge.</small></label>
    {value.authenticationMode === 'AnktSso' ? <><label>Client authentication<select value={value.clientAuthenticationMethod} onChange={e => set('clientAuthenticationMethod', e.target.value as HybridConfig['clientAuthenticationMethod'])}><option value="ClientSecretPost">Backend có client secret</option><option value="None">Public client (PKCE)</option></select></label><p className="mini-notice">S256 PKCE bắt buộc. Client secret chỉ được lưu trên máy chủ đối tác; không đưa vào JavaScript, URL hoặc WebView.</p></> : null}
  </div>;
  if (section === 3) return <div className="mini-stack"><p className="mini-muted">Chọn các quyền cần thiết. Người dùng tự cấp hoặc thu hồi quyền khi dùng ứng dụng.</p><div className="permission-grid">{permissions.filter(p => p.isActive !== false || value.permissions.includes(p.code)).map(p => <label className="permission-option" key={p.code}><input type="checkbox" disabled={value.authenticationMode === 'Independent' && (p.code.startsWith('identity.') || p.code.startsWith('profile.'))} checked={value.permissions.includes(p.code)} onChange={e => set('permissions', e.target.checked ? [...value.permissions, p.code] : value.permissions.filter(code => code !== p.code))} /><span><strong>{p.name}{p.isActive === false ? ' · Đã tắt' : ''}{p.isSensitive ? ' · Nhạy cảm' : ''}</strong><small>{p.description ?? p.code}</small><code>{p.code}</code></span></label>)}</div>{permissions.length === 0 ? <p>Chưa có quyền được phép yêu cầu.</p> : null}</div>;
  return <div className="mini-stack"><div className="mini-app-identity">{value.iconUrl ? <img src={value.iconUrl} alt={`Logo ${value.name}`} /> : <span className="mini-app-icon">{value.name.slice(0, 1) || 'A'}</span>}<div><h2>{value.name || 'Mini App mới'}</h2><p>{value.description || 'Chưa có mô tả'}</p></div></div><dl className="mini-definition"><dt>Website</dt><dd>{value.webUrl}</dd><dt>Đăng nhập</dt><dd>{value.authenticationMode === 'Independent' ? 'Tài khoản website' : 'ANKT SSO'}</dd><dt>Domain</dt><dd>{value.allowedDomains.join(', ') || 'Chưa khai báo'}</dd><dt>Quyền yêu cầu</dt><dd>{value.permissions.join(', ') || 'Không yêu cầu'}</dd><dt>Phiên bản</dt><dd>{value.version}</dd></dl><p className="mini-notice">Lưu bản nháp để xác minh domain. Sau đó gửi xét duyệt ở trang chi tiết. Ứng dụng chỉ được phát hành sau khi quản trị viên phê duyệt.</p></div>;
}
