import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { toast } from 'sonner';
import { ConfirmDialog, DataTable, ErrorView, Loading, PageHeader, Pagination, SearchBox, StatusBadge, type Column } from '../components/common';
import { ModalFrame } from '../components/ModalFrame';
import { createDeveloper, getDevelopers, transitionDeveloper } from '../services/admin-mini-app.service';
import { getErrorMessage } from '../services/http';
import type { Developer, DeveloperInput, DeveloperStatus } from '../types/mini-app';

export function DevelopersPage() {
  const client = useQueryClient(); const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [status, setStatus] = useState<DeveloperStatus | ''>(''); const [creating, setCreating] = useState(false); const [pending, setPending] = useState<{ item: Developer; action: 'approve' | 'suspend' | 'reject' }>();
  const query = useQuery({ queryKey: ['developers', page, search, status], queryFn: () => getDevelopers({ page, pageSize: 20, search: search || undefined, status: status || undefined }) });
  const mutation = useMutation({ mutationFn: () => transitionDeveloper(pending!.item.id, pending!.action), onSuccess: async () => { toast.success('Đã cập nhật Developer'); setPending(undefined); await client.invalidateQueries({ queryKey: ['developers'] }); }, onError: e => toast.error(getErrorMessage(e)) });
  const columns: Column<Developer>[] = [
    { key: 'name', title: 'Developer', render: item => <div><strong>{item.name}</strong><small className="table-subtitle">{item.companyName || item.email}</small></div> },
    { key: 'account', title: 'Tài khoản ANKT', render: item => item.accountId ? <code>{item.accountId}</code> : 'Chưa liên kết' },
    { key: 'website', title: 'Website', render: item => item.website || '—' }, { key: 'count', title: 'Mini Apps', render: item => item.miniAppCount }, { key: 'status', title: 'Trạng thái', render: item => <StatusBadge status={item.status} /> },
    { key: 'actions', title: 'Thao tác', render: item => <div className="inline-actions">{item.status === 'Pending' || item.status === 'Suspended' ? <button className="btn" onClick={() => setPending({ item, action: 'approve' })} type="button">{item.status === 'Suspended' ? 'Khôi phục' : 'Duyệt'}</button> : item.status === 'Active' ? <button className="btn danger" onClick={() => setPending({ item, action: 'suspend' })} type="button">Tạm ngừng</button> : <span className="mini-muted">Chờ Developer gửi lại hồ sơ</span>}{item.status === 'Pending' ? <button className="btn danger" type="button" onClick={() => setPending({ item, action: 'reject' })}>Từ chối</button> : null}</div> },
  ];
  return <section><PageHeader eyebrow="Đối tác" title="Developers" description="Đơn vị sở hữu Mini App, tài khoản quản lý và trạng thái truy cập nền tảng." actions={<button className="btn primary" type="button" onClick={() => setCreating(true)}>Tạo Developer</button>} /><div className="toolbar mini-toolbar"><SearchBox value={search} onChange={value => { setSearch(value); setPage(1); }} placeholder="Tên, công ty hoặc email" /><select aria-label="Trạng thái Developer" value={status} onChange={e => { setStatus(e.target.value as DeveloperStatus | ''); setPage(1); }}><option value="">Tất cả trạng thái</option>{['Pending', 'Active', 'Suspended', 'Rejected'].map(value => <option key={value}>{value}</option>)}</select></div>{query.isLoading ? <Loading /> : null}{query.isError ? <ErrorView message={getErrorMessage(query.error)} onRetry={() => void query.refetch()} /> : null}{query.data ? <><DataTable columns={columns} items={query.data.items} /><Pagination page={page} pageSize={20} total={query.data.total} onPageChange={setPage} onPageSizeChange={() => undefined} /></> : null}{pending ? <ConfirmDialog title={`${pending.action === 'approve' ? 'Duyệt' : pending.action === 'reject' ? 'Từ chối' : 'Tạm ngừng'} Developer`} description={`${pending.item.name}: quyền truy cập và mở Mini App sẽ được cập nhật ngay.`} loading={mutation.isPending} onCancel={() => setPending(undefined)} onConfirm={() => mutation.mutate()} /> : null}{creating ? <CreateDeveloperDialog onClose={() => setCreating(false)} /> : null}</section>;
}
function CreateDeveloperDialog({ onClose }: { onClose: () => void }) {
  const client = useQueryClient(); const [input, setInput] = useState<DeveloperInput>({ name: '', companyName: '', email: '', phone: '', website: '', accountId: '' });
  const create = useMutation({ mutationFn: () => createDeveloper({ ...input, accountId: input.accountId || undefined }), onSuccess: async () => { toast.success('Đã tạo Developer'); await client.invalidateQueries({ queryKey: ['developers'] }); onClose(); }, onError: e => toast.error(getErrorMessage(e)) });
  return <ModalFrame titleId="developer-create-title" onClose={onClose} busy={create.isPending}><h2 id="developer-create-title">Tạo Developer</h2><p>Liên kết tài khoản ANKT để đơn vị sử dụng Developer Portal.</p><form className="mini-stack" onSubmit={e => { e.preventDefault(); create.mutate(); }}><div className="mini-form-grid">{([{ key: 'name', label: 'Tên Developer', required: true }, { key: 'companyName', label: 'Công ty' }, { key: 'email', label: 'Email', type: 'email', required: true }, { key: 'phone', label: 'Điện thoại', type: 'tel' }, { key: 'website', label: 'Website', type: 'url' }, { key: 'accountId', label: 'ANKT Account ID' }] as const).map(field => <label key={field.key}>{field.label}<input required={'required' in field && field.required} type={'type' in field ? field.type : 'text'} pattern={field.key === 'accountId' ? '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}' : undefined} value={input[field.key] ?? ''} onChange={e => setInput({ ...input, [field.key]: e.target.value })} /></label>)}</div><div className="modal-actions"><button className="btn" type="button" disabled={create.isPending} onClick={onClose}>Hủy</button><button className="btn primary" disabled={create.isPending}>Tạo Developer</button></div></form></ModalFrame>;
}
