import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { toast } from 'sonner';
import { ConfirmDialog, DataTable, PageHeader, Pagination } from '../components/common';
import { getMiniAppAuditLogs, getMiniAppCategories, getMiniAppPermissions, getMiniAppReports, resolveMiniAppReport, saveMiniAppCategory, saveMiniAppPermission } from '../services/admin-mini-app.service';
import { getErrorMessage } from '../services/http';
import type { MiniAppCategory, MiniAppPermission, MiniAppReport } from '../types/mini-app';
import { AuditTimeline, QueryState } from '../features/developer/Shared';

export function MiniAppPolicyPage() {
  return <section><PageHeader title="Danh mục & quyền Mini App" description="Quản lý danh mục và các quyền Developer được phép yêu cầu." actions={<Link className="btn" to="/mini-apps">Quay lại Mini Apps</Link>} /><div className="detail-grid"><CategoryManagement /><PermissionManagement /></div></section>;
}
function CategoryManagement() {
  const client = useQueryClient(); const [id, setId] = useState<string>(); const [form, setForm] = useState<Omit<MiniAppCategory, 'id'>>({ name: '', slug: '', isActive: true });
  const query = useQuery({ queryKey: ['mini-app-categories'], queryFn: getMiniAppCategories });
  const mutation = useMutation({ mutationFn: () => saveMiniAppCategory(form, id), onSuccess: async () => { setId(undefined); setForm({ name: '', slug: '', isActive: true }); toast.success('Đã lưu danh mục'); await client.invalidateQueries({ queryKey: ['mini-app-categories'] }); await client.invalidateQueries({ queryKey: ['mini-app-review-metadata'] }); }, onError: e => toast.error(getErrorMessage(e)) });
  return <div className="detail-card mini-stack"><h2>Danh mục</h2><form className="mini-stack" onSubmit={e => { e.preventDefault(); mutation.mutate(); }}><label>Tên danh mục<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Slug<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" value={form.slug} onChange={e => setForm({ ...form, slug: e.target.value })} /></label><label className="check-row"><input type="checkbox" checked={form.isActive} onChange={e => setForm({ ...form, isActive: e.target.checked })} /> Cho phép sử dụng</label><div className="mini-row"><button className="btn primary" disabled={mutation.isPending}>{id ? 'Lưu danh mục' : 'Thêm danh mục'}</button>{id ? <button className="btn" type="button" onClick={() => { setId(undefined); setForm({ name: '', slug: '', isActive: true }); }}>Hủy sửa</button> : null}</div></form><QueryState query={query}><DataTable items={query.data ?? []} columns={[{ key: 'name', title: 'Danh mục', render: c => c.name }, { key: 'status', title: 'Sử dụng', render: c => c.isActive === false ? 'Đã tắt' : 'Đang bật' }, { key: 'action', title: 'Thao tác', render: c => <button className="btn" type="button" onClick={() => { setId(c.id); setForm({ name: c.name, slug: c.slug, isActive: c.isActive ?? true }); }}>Sửa</button> }]} /></QueryState></div>;
}
function PermissionManagement() {
  const client = useQueryClient(); const [editing, setEditing] = useState<string>(); const [form, setForm] = useState<MiniAppPermission>({ code: '', name: '', description: '', isSensitive: false, isActive: true });
  const query = useQuery({ queryKey: ['mini-app-permissions'], queryFn: getMiniAppPermissions });
  const reset = () => { setEditing(undefined); setForm({ code: '', name: '', description: '', isSensitive: false, isActive: true }); };
  const mutation = useMutation({ mutationFn: () => saveMiniAppPermission(form, editing), onSuccess: async () => { reset(); toast.success('Đã lưu quyền'); await client.invalidateQueries({ queryKey: ['mini-app-permissions'] }); await client.invalidateQueries({ queryKey: ['mini-app-review-metadata'] }); }, onError: e => toast.error(getErrorMessage(e)) });
  return <div className="detail-card mini-stack"><h2>Quyền được phép yêu cầu</h2><form className="mini-stack" onSubmit={e => { e.preventDefault(); mutation.mutate(); }}><label>Mã quyền<input required readOnly={Boolean(editing)} pattern="[a-z][a-z0-9_.-]+" value={form.code} onChange={e => setForm({ ...form, code: e.target.value })} /></label><label>Tên quyền<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Mô tả<textarea rows={3} value={form.description ?? ''} onChange={e => setForm({ ...form, description: e.target.value })} /></label><label className="check-row"><input type="checkbox" checked={form.isSensitive} onChange={e => setForm({ ...form, isSensitive: e.target.checked })} /> Quyền nhạy cảm</label><label className="check-row"><input type="checkbox" checked={form.isActive ?? true} onChange={e => setForm({ ...form, isActive: e.target.checked })} /> Cho phép yêu cầu</label><div className="mini-row"><button className="btn primary" disabled={mutation.isPending}>{editing ? 'Lưu quyền' : 'Thêm quyền'}</button>{editing ? <button className="btn" type="button" onClick={reset}>Hủy sửa</button> : null}</div></form><QueryState query={query}><DataTable items={(query.data ?? []).map(p => ({ ...p, id: p.code }))} columns={[{ key: 'name', title: 'Quyền', render: p => <><strong>{p.name}</strong><small className="table-subtitle">{p.code}{p.isSensitive ? ' · Nhạy cảm' : ''}</small></> }, { key: 'status', title: 'Yêu cầu', render: p => p.isActive === false ? 'Đã tắt' : 'Đang bật' }, { key: 'edit', title: 'Thao tác', render: p => <button className="btn" type="button" onClick={() => { setEditing(p.code); setForm({ code: p.code, name: p.name, description: p.description, isSensitive: p.isSensitive, isActive: p.isActive ?? true }); }}>Sửa</button> }]} /></QueryState></div>;
}
export function MiniAppReportsPage() {
  const client = useQueryClient(); const [page, setPage] = useState(1); const [pending, setPending] = useState<MiniAppReport>(); const [reason, setReason] = useState('');
  const query = useQuery({ queryKey: ['mini-app-reports', page], queryFn: () => getMiniAppReports(page) });
  const mutation = useMutation({ mutationFn: () => resolveMiniAppReport(pending!.id, reason.trim()), onSuccess: async () => { setPending(undefined); setReason(''); toast.success('Đã xử lý báo cáo'); await client.invalidateQueries({ queryKey: ['mini-app-reports'] }); }, onError: e => toast.error(getErrorMessage(e)) });
  return <section><PageHeader title="Báo cáo Mini App" description="Xem phản ánh của người dùng và ghi nhận kết quả xử lý." actions={<Link className="btn" to="/mini-apps">Quay lại</Link>} /><QueryState query={query}><DataTable items={query.data?.items ?? []} columns={[{ key: 'app', title: 'Mini App', render: item => <Link to={`/mini-apps/${item.miniAppId}`}>{item.appName}</Link> }, { key: 'reason', title: 'Phản ánh', render: item => item.reason }, { key: 'status', title: 'Kết quả', render: item => item.resolution || 'Chưa xử lý' }, { key: 'date', title: 'Ngày gửi', render: item => new Date(item.createdAt).toLocaleString('vi-VN') }, { key: 'action', title: 'Thao tác', render: item => !item.resolvedAt ? <button className="btn" type="button" onClick={() => setPending(item)}>Xử lý</button> : 'Đã xử lý' }]} /><Pagination page={page} pageSize={20} total={query.data?.total ?? 0} onPageChange={setPage} onPageSizeChange={() => undefined} /></QueryState>{pending ? <ConfirmDialog title="Xử lý báo cáo Mini App" description={pending.reason} confirmText="Lưu kết quả" confirmDisabled={reason.trim().length < 3} loading={mutation.isPending} onCancel={() => { setPending(undefined); setReason(''); }} onConfirm={() => mutation.mutate()}><label className="mini-stack">Kết quả xử lý<textarea rows={4} value={reason} onChange={e => setReason(e.target.value)} /></label></ConfirmDialog> : null}</section>;
}
export function MiniAppAuditPage() {
  const [page, setPage] = useState(1); const [id, setId] = useState(''); const query = useQuery({ queryKey: ['mini-app-audit-all', page, id], queryFn: () => getMiniAppAuditLogs({ page, pageSize: 20, miniAppId: id || undefined }) });
  return <section><PageHeader title="Nhật ký Mini App" description="Hoạt động quản lý, bảo mật và xét duyệt trên nền tảng." actions={<Link className="btn" to="/mini-apps">Quay lại</Link>} /><div className="detail-card mini-stack"><label>Lọc theo Mini App ID<input value={id} onChange={e => { setId(e.target.value); setPage(1); }} /></label><QueryState query={query}><AuditTimeline items={query.data?.items ?? []} /><Pagination page={page} pageSize={20} total={query.data?.total ?? 0} onPageChange={setPage} onPageSizeChange={() => undefined} /></QueryState></div></section>;
}
