import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ImagePlus, RefreshCw, Sticker as StickerIcon } from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';
import { DataTable, ErrorView, Loading, PageHeader, type Column } from '../components/common';
import { createSticker, createStickerPack, getStickerPack, getStickerPacks, setStickerActive, setStickerPackActive, updateStickerPack, uploadStickerImage } from '../services/admin-sticker.service';
import { getErrorMessage } from '../services/http';
import type { AdminStickerPack, SaveStickerPack } from '../types/sticker';

const emptyPack: SaveStickerPack = { name: '', description: null, thumbnailUrl: '', price: 0, isFeatured: false, isActive: true, sortOrder: 0, availableFrom: null, availableUntil: null };

export function StickerPacksPage() {
  const client = useQueryClient(); const [selectedId, setSelectedId] = useState(''); const [draft, setDraft] = useState(emptyPack); const [stickerName, setStickerName] = useState(''); const [stickerUrl, setStickerUrl] = useState('');
  const packs = useQuery({ queryKey: ['sticker-packs'], queryFn: getStickerPacks });
  const detail = useQuery({ queryKey: ['sticker-pack', selectedId], queryFn: () => getStickerPack(selectedId), enabled: Boolean(selectedId) });
  const refresh = async () => { await client.invalidateQueries({ queryKey: ['sticker-packs'] }); if (selectedId) await client.invalidateQueries({ queryKey: ['sticker-pack', selectedId] }); };
  const savePack = useMutation({ mutationFn: () => selectedId ? updateStickerPack(selectedId, draft) : createStickerPack(draft), onSuccess: async (pack) => { toast.success(selectedId ? 'Đã cập nhật bộ nhãn dán' : 'Đã tạo bộ nhãn dán'); setSelectedId(pack.id); await refresh(); }, onError: (error) => toast.error(getErrorMessage(error)) });
  const columns: Column<AdminStickerPack>[] = [
    { key: 'name', title: 'Bộ nhãn dán', render: (item) => <div className="sticker-pack-cell"><img alt="" src={item.thumbnailUrl} /><strong>{item.name}</strong></div> },
    { key: 'count', title: 'Nhãn dán', render: (item) => item.stickerCount }, { key: 'price', title: 'Giá', render: (item) => item.price === 0 ? 'Miễn phí' : `${item.price.toLocaleString('vi-VN')} xu` },
    { key: 'owners', title: 'Sở hữu', render: (item) => item.ownerCount }, { key: 'usage', title: 'Lượt dùng', render: (item) => item.usageCount },
    { key: 'status', title: 'Trạng thái', render: (item) => <button className={`btn ${item.isActive ? 'secondary' : 'ghost'}`} onClick={(event) => { event.stopPropagation(); void setStickerPackActive(item.id, !item.isActive).then(refresh); }} type="button">{item.isActive ? 'Đang hiện' : 'Đang ẩn'}</button> },
  ];
  return <section><PageHeader eyebrow="Nội dung chat" title="Nhãn dán" description="Quản lý bộ nhãn dán, ảnh CDN, giá và trạng thái mà không xoá lịch sử chat." actions={<button className="btn secondary" onClick={() => void refresh()} type="button"><RefreshCw size={16} /> Làm mới</button>} />
    <div className="admin-sticker-grid"><div>{packs.isLoading ? <Loading /> : null}{packs.isError ? <ErrorView message={getErrorMessage(packs.error)} onRetry={() => void packs.refetch()} /> : null}{packs.data ? <DataTable columns={columns} items={packs.data} onRowClick={(item) => { setSelectedId(item.id); setDraft({ name: item.name, description: item.description, thumbnailUrl: item.thumbnailUrl, price: item.price, isFeatured: item.isFeatured, isActive: item.isActive, sortOrder: item.sortOrder, availableFrom: item.availableFrom, availableUntil: item.availableUntil }); }} /> : null}</div>
      <aside className="sticker-editor"><div className="section-heading"><h2>{selectedId ? 'Sửa bộ nhãn dán' : 'Tạo bộ nhãn dán'}</h2>{selectedId ? <button className="btn ghost" onClick={() => { setSelectedId(''); setDraft(emptyPack); }} type="button">Tạo mới</button> : null}</div><label>Tên<input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} /></label><label>Thumbnail HTTPS<input value={draft.thumbnailUrl} onChange={(e) => setDraft({ ...draft, thumbnailUrl: e.target.value })} /></label>{selectedId ? <label className="btn secondary"><ImagePlus size={16} /> Upload thumbnail<input accept="image/png,image/webp" hidden type="file" onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadStickerImage(selectedId, file).then((thumbnailUrl) => setDraft((value) => ({ ...value, thumbnailUrl }))).catch((error) => toast.error(getErrorMessage(error))); }} /></label> : null}<label>Giá xu<input min="0" type="number" value={draft.price} onChange={(e) => setDraft({ ...draft, price: Number(e.target.value) })} /></label><label>Thứ tự<input type="number" value={draft.sortOrder} onChange={(e) => setDraft({ ...draft, sortOrder: Number(e.target.value) })} /></label><label>Mở từ<input type="datetime-local" value={draft.availableFrom?.slice(0, 16) ?? ''} onChange={(e) => setDraft({ ...draft, availableFrom: e.target.value ? new Date(e.target.value).toISOString() : null })} /></label><label>Đến<input type="datetime-local" value={draft.availableUntil?.slice(0, 16) ?? ''} onChange={(e) => setDraft({ ...draft, availableUntil: e.target.value ? new Date(e.target.value).toISOString() : null })} /></label><label className="check"><input checked={draft.isFeatured} type="checkbox" onChange={(e) => setDraft({ ...draft, isFeatured: e.target.checked })} /> Nổi bật</label><label className="check"><input checked={draft.isActive} type="checkbox" onChange={(e) => setDraft({ ...draft, isActive: e.target.checked })} /> Hiển thị</label><button className="btn primary" disabled={!draft.name || !draft.thumbnailUrl || savePack.isPending} onClick={() => savePack.mutate()} type="button"><StickerIcon size={16} /> {selectedId ? 'Lưu thay đổi' : 'Tạo bộ'}</button></aside></div>
    {selectedId && <section className="sticker-detail"><h2>{detail.data?.pack.name ?? 'Chi tiết bộ nhãn dán'}</h2><div className="sticker-upload-row"><label className="btn secondary"><ImagePlus size={16} /> Upload PNG/WebP<input accept="image/png,image/webp" hidden type="file" onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadStickerImage(selectedId, file).then(setStickerUrl).catch((error) => toast.error(getErrorMessage(error))); }} /></label><input placeholder="Tên nhãn dán" value={stickerName} onChange={(e) => setStickerName(e.target.value)} /><input placeholder="Image URL" value={stickerUrl} onChange={(e) => setStickerUrl(e.target.value)} /><button className="btn primary" onClick={() => void createSticker(selectedId, { name: stickerName, imageUrl: stickerUrl, thumbnailUrl: null, format: stickerUrl.toLowerCase().endsWith('.png') ? 0 : 1, sortOrder: detail.data?.stickers.length ?? 0, isActive: true }).then(async () => { setStickerName(''); setStickerUrl(''); await refresh(); })} type="button">Thêm</button></div><div className="sticker-admin-list">{detail.data?.stickers.map((item) => <article key={item.id}><img alt={item.name} src={item.imageUrl} /><strong>{item.name}</strong><button className="btn ghost" onClick={() => void setStickerActive(item.id, !item.isActive).then(refresh)} type="button">{item.isActive ? 'Ẩn' : 'Hiện'}</button></article>)}</div></section>}
  </section>;
}
